### ISSUE TITLE
akick won't work in this sceneraio.

### ISSUE THREAD

**Issue by DTSCode** [tonyravioli/dongerdong#27]
In #donger on freenode, User rotta666 and I have been doing deathmatches, and we both recieve instakills. After getting kicked, we were able to rejoin the channel, which i found odd, since it was a deathmatch. Upon closer inspection, it appears as though it is because akick doesn't work on +r (registered) users. However, it still bans just fine on deathmatches with no instakill. If you would like to assign this issue to me I would be more than happy to dig through my fork and find it.

**Comment by Polsaker** [comment]
Works as intended. There is no akick when a deathmatch is finised by an instakill because of its OPness.
