### ISSUE TITLE
!stats are not printed if the user is not in the channel

### ISSUE THREAD

**Issue by tonyravioli** [tonyravioli/dongerdong#38]
!stats <user> returns `There are no registered stats for <user>` when the user isn't in the channel.

**Comment by Polsaker** [comment]
try with the account name?

**Comment by tonyravioli** [comment]
It works with the account name, but that's not typically what people search for when they do `!stats`.

**Comment by Polsaker** [comment]
The only solution for this would be to keep a huge database mapping nicks to account names.
