### ISSUE TITLE
Idles and quits should count as deaths...

### ISSUE THREAD

**Issue by tonyravioli** [tonyravioli/dongerdong#48]
...with the credit for the kill being awarded to the person's opponent (or the last person to hit them if it's multi-player). I think that's working now (giving easy wins), but they should be kicked as well (which isn't happening now).

Idles and quits in deathmatches should cause a bant (just like if they lost the normal way), but should also incur a fine of 10 dongcoins (to be given to the victor, along with the normal 10 coins for winning).

**Comment by Polsaker** [comment]
Idleouts are now counted as their own stat, and idlers are banned in deathmatches, also, the coins were removed in the rewrite since nobody used them.
