### ISSUE TITLE
Bot should have support for IRCds lacking v3

### ISSUE THREAD

**Issue by kernelpanic3** [tonyravioli/dongerdong#69]
(e.g. InspIRCd)

I'm sure I could probably hack something together by going back through old commits, but...it would be really nice not to have to.

Thanks for a dongy donger bot. :)

**Comment by Polsaker** [comment]
dongerdong uses WHOX to keep track of who's identified with nickserv, and [inspircd still doesn't support that](https://github.com/inspircd/inspircd/issues/31). The previous version of the bot had a silly workaround for that (it flooded the server with WHOIS queries). With the current code, we have to write a pydle extension.

Also, related: lykoss/lykos#112
