### ISSUE TITLE
Feature request: option to disable ASCII art

### ISSUE THREAD

**Issue by kernelpanic3** [tonyravioli/dongerdong#70]
The bot works beautifully now, but one of its players is blind, and uses a screen reader to IRC. Screen readers don't handle ASCII art very well, and it can easily interfere with his ability to keep track of the fight.

Would it be possible to implement a config option to disable ASCII art entirely, to accommodate for this?

**Comment by tonyravioli** [comment]
I'll move the ascii command over to extcmd.

**Comment by tonyravioli** [comment]
Scratch that, since an extcmd would only do the !ascii command, I'll implement a config argument.
